"""empty message

Revision ID: 779014da5b3d
Revises: f58846daf788
Create Date: 2016-02-04 12:41:50.300585

"""

# revision identifiers, used by Alembic.
revision = '779014da5b3d'
down_revision = 'f58846daf788'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'slug')
    ### end Alembic commands ###
